netvl/xml-rs

src/namespace.rs
Fixes compiler errors in the latest nightly.
=> Fix rename hash_map::Entries -> hash_map::Iter

Readme.md
Change uint -> usize
Rust enums need namespacing (maybe replace the glob importwith an explicit `xml::reader::events::XmlEvent`?)
Put the `match parser.next()` snippet inside a code block
=> Update Readme.md example

src/escape.rs, src/name.rs, src/namespace.rs, src/util.rs
There are changes to public-facing types in `src/util.rs` - the old way needed a bunch of `PhantomFn` and `PhantomData` type annotations.
=> New Borrow + IntoChanged, remove BorrowFrom, juggle types.

src/escape.rs, src/reader/parser.rs, src/writer/mod.rs
I fixed error about obsolete syntax with closure and removed deprecated CowString and MemWriter.
=> Fixed compilation error and removed deprecated stuff for rustc 1.0.0-dev (890293655 2015-02-28).

src/reader/lexer.rs, src/reader/mod.rs, src/reader/parser.rs
1) Don't hard wire BufReader when not necessary -- the choice of the implementation should be left up to the client
2) Change constructor names to align with rust standard naming scheme
=> Don't specialize on BufReader & Follow standard naming

src/reader/lexer.rs
In the lexer, a buffer is allocated each time a code point has to be read. Reusing the same buffer represents a small optimization (though it could be removed with any refactoring of the parser). On my machine, I can run the parsing loop at 6.5MB/s instead of 5.4MB/s.
I hope that I did not break anything.
=> Attempt to remove memory allocation

src/reader/lexer.rs, src/reader/parser/inside_cdata.rs, src/reader/parser/inside_comment.rs, src/reader/parser/mod.rs, src/reader/parser/outside_tag.rs
I was using `xml-rs` to parse a fairly large amount of XML data, but ran into some serious performance issues. While it took Go's `encoding/xml` about 3 mins to parse all of my data, my Rust version took over 20 mins before I had to stop it.
Profiling the code, I found, that the only real bottleneck was `Token`s being reverted to strings with `to_string` (through `fmt::Display`) in most calls to `append_str_continue` (called a lot by methods called by `dispatch_event`). These calls use the whole `fmt` infrastructure, then allocate a `String`, just to borrow it and push it unto another `String`. I added a method `push_to_string` for `Token` that does this with no allocations/formatting, and replaced `append_str_continue` and calls to it with this.
I mainly patched this for my own use, but …
=> Removed calls to the slow `token.to_string()`

Cargo.toml, src/util.rs
This fixes warnings future warnings, but those warnings are about things that should not be valid and it compiles on stable, unless someone was trying to doing something bogus.
=> Implementors of IteratorClonedPairwiseExt must implement Sized

src/writer/mod.rs
Previously it couldn't be named as it was in a private module
=> Make EmitterError nameable

src/reader/parser/mod.rs, tests/event_reader.rs
From http://www.w3.org/TR/REC-xml-names/#defaulting
> The namespace name for an unprefixed attribute name always has no value.
However, I find that `OwnedAttribute` instances from the `EventReader` end up inheriting the default namespace, which I don't think is entirely right. This pull request should fix that.
Thanks,
=> Non-namespaced attributes seem to inherit default namespace

src/reader/error.rs, src/reader/error_impl.rs, src/reader/lexer.rs, src/reader/mod.rs, src/reader/parser/mod.rs
Issue #106: This time it should be okay.
The tests are passed.
The error is popped up to the very `EventReader::next` call.
The EventReader's source is accessible via `er.source()` and `er.source_mut()`.
I'm still not sure whether it is convenient to dive into the cases of `reader::Error` though...
=> Issue #106: Fix I/O error handling in lexer and parser (attempt #3)

src/writer/mod.rs
This is useful, for example, if you want to incorporate an `EventWriter<Vec<u8>>` into a structure, and then get the vector when you're done consuming input.
=> Add into_inner() method for EventWriter so that we can get the underlying writer back after we're finished

Cargo.toml, src/reader/error.rs, tests/event_reader.rs
This allows users to use `try!(File::open(…))` or other IO-related things in a function that also does XML parsing and returns `xml::reader::Result`.
See the added function in `tests/event_reader.rs` for an example.
=> Implement From<std::io::Error> for xml::reader::Error

Cargo.toml
0.5 was the last version that allows Rust <1.8.
=> Allow bitflags 0.5 and 0.6

src/common.rs
xml::common::XmlVersion is public, but it does not have the Debug trait, making it difficult to use in external structures which do implement Debug.
This change fixes it.
=> Add missing Debug impl for XmlVersion

src/escape.rs
```rust
writer.write(XmlEvent::characters("☃<")).unwrap();
```
This code causes panic on [this line](https://github.com/netvl/xml-rs/blob/6febe3a04b46abcc6d90f3916b1fbc07c8074410/src/escape.rs#L46). The problem is `i` was a number of characters, not bytes.
```
thread 'main' panicked at 'byte index 1 is not a char boundary; it is inside '☃' (bytes 0..3) of `☃<`'
```
=> Fix escaping multibyte string

src/reader/config.rs, src/reader/parser/inside_reference.rs, tests/documents/sample_5.xml, tests/documents/sample_5_short.txt, tests/event_reader.rs
This is useful to parse xhtml files that contains custom html entities like &amp;nbsp; or &amp;copy;
I'm writting an [epub reader lib][1] and I'm having problems parsing xhtml files that contains &amp;nbsp; so I need a way to deal with this.
[Currently I've done a workaround][2], removing the unexpected entities from the source xhtml before parse it, but it could be great to be able to configure this in the ParserConfig.
At first I thought about a simple boolean configuration to "ignore_unexpected_entities", but then I thought that it could be better to be able to add custom entities to the parser so that is what I've done in this pull request.
[1]: https://github.com/danigm/epub-rs
[2]: https://github.com/danigm/epub-rs/commit/cdb9bbc82e5c510ae1e5301f6f3ae9f80444efbf
=> Adding extra entities configuration in ParserConfig

src/writer/events.rs
The writer::XmlEvent structure had no Debug impl despite being public.
=> Add Debug to writer::XmlEvent

src/reader/config.rs, src/reader/lexer.rs, src/reader/mod.rs, src/reader/parser/mod.rs, tests/streaming.rs
Hello,
I'm working on an xmpp library and I need to be able to reopen the parser to consume new bytes.
It's a first step to be able to reset some condition, I use it like that:
```rust
loop {
// My parser is an instance of EventReader<Buffer>,
// Buffer is a custom struct that hold my buffer and expose some useful methods.
// It implement Read 
if self.parser.source().available_data() > 0 {
self.parser.reopen_parser();
}
match self.parser.next() { ... }
}
```
What do you think?
Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>
=> Proposal: Stream support reopen parser

src/common.rs, src/reader/config.rs, src/reader/parser/inside_reference.rs, tests/documents/sample_5.xml, tests/documents/sample_5_short.txt, tests/event_reader.rs
Some entities doesn't have one char, like &NotEqualTilde; so we need to
enable the use of String instead of char for parse entities.
This change fixes the bug report: https://github.com/netvl/xml-rs/issues/149
=> Using string instead of char to convert XML entities

src/common.rs
Ref:  https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-NameChar
Closes netvl/xml-rs#179
=> Fix is_name_char transcription error.

Cargo.toml, src/analyze.rs, src/lib.rs, tests/event_reader.rs, tests/event_writer.rs, tests/streaming.rs
This builds upon and closes https://github.com/netvl/xml-rs/pull/172
* Addressed review feedback from that PR:
* Moved comment
* Made lazy_static only a `[dev-dependencies]`
* Added `#![forbid(unsafe_code)]` to all entry points, which makes tools like `cargo geiger` happy.  These can of course be removed in the future if a good reason to use unsafe code comes up, but one of the big draws of this library, to me, is that it's - so far - 100% safe rust code.  Which makes me a lot less nervous about parsing potentially hostile/malicious user input with it.
=> Remove use of unsafe in favor of lazy_static!. Round 2

src/reader/lexer.rs, src/writer/emitter.rs, tests/event_reader.rs
This PR adjusts xml-rs to better ignore the contents of a DTD in an xml file, solving #170.  This just skips the entire DTD in the lexer for now.
I also ran into this for some xml files locally, but also did not need the DTD information.
This PR also fixes a compiler warning and the test suite failures caused by upgrading to rust 1.28.
=> Better handle/ignore doctypes

Cargo.toml, src/reader/reading/logic/mod.rs, src/reader/reading/logic/parsers.rs, src/reader/reading/mod.rs
nom_locate 2.0 released in February, makes some formerly-public
struct fields private and replaces them with method calls.
=> Update to nom_locate 2.0 release

src/reader/config.rs, src/reader/parser/inside_reference.rs, tests/event_reader.rs
Make it possible for the parser to successfully parse an XML document that contains entity references for surrogate pairs.
A document that contains a character entity reference that resolves to a surrogate pair – for example `<doc>&#xd83d;&#xdd34;</doc>` – is *technically* invalid according to the XML specification. However, replacing these with U+FFFD is both better for the consuming application (because the application does not need to do some weird pre-processing of the document before parsing it) and has precedent in that the standard Go XML parser in its standard configuration replaces these with U+FFFD.
Add an option – disabled by default – to ParserConfig that allows this translation when these entity references are encountered.
---
Fixes #187
_Note: this is mutually exclusive with …
=> Option to allow surrogate pair entity references 

src/writer/config.rs, src/writer/emitter.rs, tests/event_writer.rs
This config option sets whether to add a space before `/>` in
self-closing tags. Example behavior:
true -> `<a />`,
false -> `<a/>`
This commit also adds a single test to test the `false` case of this config
option, as it is set to `true` by default.
=> Add pad_self_closing config option

src/reader/config.rs, src/reader/parser/outside_tag.rs, tests/documents/sample_6.xml, tests/documents/sample_6_full.txt, tests/event_reader.rs
While trying to implement XML canonicalization I realized I couldn't distinguish between the following documents:
```
<a/><a/>
```
```
<a/>
<a/>
```
```
<a/>
<a/>
```
This is because the newline isn't emitted because it's at the root level.
This extra flag will cause a new line to be emitted, which will provide enough information to do proper canonicalization.
=> adds ParseConfig ignore_root_level_whitespace option

src/writer/emitter.rs
On Linux writes will partially complete when hitting a 4096 byte boundary (though this could happen on all OSs). This ensures that all bytes will be written to the writer.
=> fix: Make sure all bytes are written to the writer

src/writer/emitter.rs
The 'characters' writer event could not be used to output text after
the document declaration, only before it or after the first XML element.
This change ensures that the document declaration will be output before
the text.  Arbitrary text can still be output at the start of the file,
if needed, by writing directly using the inner_mut method.
Addresses issue #168.
=> Fix issue #168:  Force XML document declaration to be output before 'characters' event

src/reader/lexer.rs, tests/event_reader.rs
I was playing around with xml-rs in my own project (https://github.com/jdalberg/cwmp) and decided to use QuickCheck for validation. So a bunch of randomness into fields, generate some xml, parse it and compare with input with different permutation of content, and came across what I consider to be a bug in the parser. It would not recoqnice: "?>" as characters.
Looking into xml-rs i could see that in line 127 of reader/lexer.rs the token for "?>" was missing from the function, looking at issue #32 i introduced two new testcases and the two tokens for "]]>" and "?>" in the list of token that are possibly characters.
=> Attempted to fix the parsing as characters of ]]> and ?>

src/reader/mod.rs, tests/event_reader.rs
Can be useful for code that reads nested element trees in various places
and wants to skip known or unknown elements that are not of interest.
This way it doesn't need to maintain depth state and skip manually in
all those places.
=> reader: add EventReader::skip() convenience function to skip subtrees

src/common.rs, src/name.rs, src/reader/error.rs, src/reader/lexer.rs, src/reader/mod.rs, src/reader/parser/inside_closing_tag_name.rs, src/reader/parser/inside_comment.rs, src/reader/parser/inside_declaration.rs, src/reader/parser/inside_opening_tag.rs, src/reader/parser/inside_processing_instruction.rs, src/reader/parser/inside_reference.rs, src/reader/parser/mod.rs, src/reader/parser/outside_tag.rs
I've noticed that the error handling in this crate is highly relying on Strings (or `Cow<'static, str>`, which isn't much better). This is a problem mainly for tests, performance and reliability - error cases allocate unnecessarily, tests can only compare via the `.description()` message (which is unreliable, you should never cast something to a String to compare the String, if it is possible to just compare the enum directly). Meaning, you can't change the error message, without everything failing - everything is stringly typed. And lastly, there is no overview over what errors can actually occur (because a String could be anything, doesn't say anything about what type of error can occur).
During making this change I needed to remove the `msg()` function of the `Error`. …
=> Refactored error handling to strong typing

src/reader/lexer.rs
Avoid entering `unreachable!()` when displaying an error message for an invalid `<!` token. This fixes a panic when processing a malformed XML which contains such token in an unexpected place.
Find below a minimal reproducer and the resulting backtrace:
```rust
use std::io;
use xml::ParserConfig;
fn main() {
let source = "<!DOCTYPEs/%<!A";
let parser = ParserConfig::new()
.cdata_to_characters(true)
.ignore_comments(true)
.coalesce_characters(false)
.create_reader(io::Cursor::new(source));
for e in parser {
println!("{:?}", e);
}
}
```
```
Ok(StartDocument(1.0, UTF-8, None))
thread 'main' panicked at 'internal error: entered unreachable code', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xml-rs-0.8.13/src/reader/lexer.rs:84:47
stack backtrace:
0: rust_begin_unwind
at …
```
=> Avoid panic when displaying unexpected token error
